install:
- nuget restore
- cmd: nuget install redis-64 -excludeversion
- cmd: redis-64\redis-server.exe --service-install 
- cmd: redis-64\redis-server.exe --service-start

configuration: Debug

before_build:
- nuget restore

build:
  project: StackCache.sln
  
environment:
  COVERALLS_REPO_TOKEN:
    secure: kwZmZVMlkMBfoLy7tJOcm4emlFLrdRkvoIKbGSKXTDQ/21dbDg30yrSG5/dvtEJ0

after_test:
- packages\OpenCover.4.6.210-rc\tools\OpenCover.Console.exe -register:user -target:"packages\xunit.runner.console.2.0.0\tools\xunit.console.exe" -targetargs:"StackCache.Test\bin\Debug\StackCache.Test.dll -noshadow" -filter:"+[StackCache*]* -[StackCache.Test]*" -output:opencovertests.xml -coverbytest:*.Test.dll
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover opencovertests.xml --debug
